# config.toml

title = "Base Configuration for chunk_rclone.py"

# [rclone_paths] # remote_name is now expected in the control file for each job.
# No default job paths here; jobs are defined by control files.

[rclone_options]
# Default flags passed to rclone copy command.
# These will be used unless a control file overrides the entire [rclone_options] section
# or provides its own 'flags' list within an [rclone_options] section.
flags = [
    "-v",                # Verbose - for more detail, use "-vv"
    "--tpslimit", "8",
    "--tpslimit-burst", "10",
    "--retries", "5",
    "--checkers", "4",
    "--transfers", "2",
    "--stats", "30s",
    "--stats-one-line"
]

[chunking]
# Default duration for each rclone chunk in seconds if not specified in control file.
run_duration_seconds = 3600 # 1 hour

[logging]
# Default local directory for rclone chunk logs.
log_dir = "rclone_chunk_logs_py"
# Default base name for local chunk log files. Control file can override.
log_file_basename = "rclone_chunk" # Generic basename

# Default for uploading logs. Control file can override.
upload_logs_to_remote = false
# remote_log_upload_path is NOT defined here; MUST be in control file if upload_logs_to_remote is true.
